# Rule for generating the main program
1-2thread: 1-2thread.o 
	gcc 1-2thread.c -o 1-2thread -lpthread

# Compile source files
1-2thread.o : 1-2thread.c
	gcc -c 1-2thread.c

# Clean object files
clean :
	rm -f 1-2thread.o 
