# Rule for generating the main program
1-1pointer2 : 1-1pointer2.o
	gcc 1-1pointer2.o -o 1-1pointer2


# Compile source files
1-1pointer2.o : 1-1pointer2.c
	gcc -c 1-1pointer2.c

# Clean object files
clean :
	rm 1-1pointer2.o
