# Rule for generating the main program
1-1person : 1-1person.o
	gcc 1-1person.o -o 1-1person

# Compile source files
1-1person.o :1-1person.c
	gcc -c 1-1person.c

# Clean object files
clean :
	rm -f 1-1person.o
