# Rule to build the main program
1-1output : 1-1output.o
	gcc 1-1output.o -o 1-1output

# Sources compilation
1-1output.o : 1-1output.c
	gcc -c 1-1output.c


# Clean object files
clean :
	rm -f 1-1output.o