# Rule for generating the main program
1-1copy : 1-1copy.o 
	gcc 1-1copy.o   -o 1-1copy



# Compile source files
1-1copy.o : 1-1copy.c  
	gcc -c 1-1copy.c

# Clean object files
clean :
	rm -f 1-1copy.o